name: genex_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: any
  http: ^1.2.1

  webview_flutter: ^4.7.0
  flutter_tts: ^4.2.2
  speech_to_text: ^7.0.0
  dio: ^5.4.0
  model_viewer_plus: ^1.7.0
  flutter_riverpod: ^2.3.7
  shared_preferences: ^2.2.0
  cupertino_icons: ^1.0.8
  web_socket_channel: ^3.0.3
  file_picker: ^6.1.1
  flutter_local_notifications: ^18.0.1

  google_fonts: ^6.2.1
  flutter_animate: ^4.5.2
  shimmer: ^3.0.0
  fl_chart: ^0.69.0
  lottie: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/models/dna.glb
    - assets/models/dnagreen.glb
    - assets/models/dnaorange.glb
    - assets/models/dnared.glb
    - assets/images/genex_logo.jpeg