// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIIJFg2DPbE6LaQiJ5GUpcsbNEwpakGuw',
    appId: '1:614852656255:web:9b4ee4fb0c39a5edfed34a',
    messagingSenderId: '614852656255',
    projectId: 'genex-aa039',
    authDomain: 'genex-aa039.firebaseapp.com',
    storageBucket: 'genex-aa039.firebasestorage.app',
    measurementId: 'G-F6B7WE411T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu6QFHUfDsvgNKbU9CUgzQnMY6MGxdWmU',
    appId: '1:614852656255:android:4f0941ef76d407bcfed34a',
    messagingSenderId: '614852656255',
    projectId: 'genex-aa039',
    storageBucket: 'genex-aa039.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD95CvPpMS3G5znXWipA14x9o1o00umFIA',
    appId: '1:614852656255:ios:85ccb4205cd0b923fed34a',
    messagingSenderId: '614852656255',
    projectId: 'genex-aa039',
    storageBucket: 'genex-aa039.firebasestorage.app',
    iosBundleId: 'com.example.genexApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD95CvPpMS3G5znXWipA14x9o1o00umFIA',
    appId: '1:614852656255:ios:85ccb4205cd0b923fed34a',
    messagingSenderId: '614852656255',
    projectId: 'genex-aa039',
    storageBucket: 'genex-aa039.firebasestorage.app',
    iosBundleId: 'com.example.genexApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIIJFg2DPbE6LaQiJ5GUpcsbNEwpakGuw',
    appId: '1:614852656255:web:95a0e61f11367148fed34a',
    messagingSenderId: '614852656255',
    projectId: 'genex-aa039',
    authDomain: 'genex-aa039.firebaseapp.com',
    storageBucket: 'genex-aa039.firebasestorage.app',
    measurementId: 'G-NQNV2QN1QQ',
  );
}
