# Generated by Django 5.2.8 on 2026-02-01 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_symptomreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_username', models.CharField(max_length=150)),
                ('patient_username', models.CharField(max_length=150)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('appointment_date', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
