# Generated by Django 5.2.8 on 2026-04-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_doctorpatient'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_1', models.CharField(db_index=True, max_length=255)),
                ('drug_2', models.CharField(db_index=True, max_length=255)),
                ('interaction_description', models.TextField()),
            ],
        ),
    ]
