# Generated by Django 5.2.8 on 2026-04-14 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_genepredictionreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_gene_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_user', to='api.fileupload'),
        ),
        migrations.CreateModel(
            name='TwinRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_drugs', models.JSONField()),
                ('results', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twin_runs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
