# Generated by Django 5.2.8 on 2026-04-16 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_user_current_gene_file_twinrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('esr', models.FloatField(blank=True, null=True)),
                ('crp', models.FloatField(blank=True, null=True)),
                ('rf', models.FloatField(blank=True, null=True)),
                ('anti_ccp', models.FloatField(blank=True, null=True)),
                ('c3', models.FloatField(blank=True, null=True)),
                ('c4', models.FloatField(blank=True, null=True)),
                ('ana', models.BooleanField(default=False)),
                ('anti_sm', models.BooleanField(default=False)),
                ('anti_ro', models.BooleanField(default=False)),
                ('hla_b27', models.BooleanField(default=False)),
                ('anti_la', models.BooleanField(default=False)),
                ('anti_dsdna', models.BooleanField(default=False)),
                ('disease_prediction', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('xai_explanation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_test_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
