# Generated by Django 5.2.8 on 2026-04-16 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_user_current_gene_file_twinrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwinSimulationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug1', models.CharField(max_length=255)),
                ('drug2', models.CharField(blank=True, max_length=255, null=True)),
                ('file_name', models.CharField(max_length=255)),
                ('best_drug', models.CharField(max_length=255)),
                ('risk_reduction', models.FloatField(default=0)),
                ('hits', models.IntegerField()),
                ('full_report', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
