# Generated by Django 5.2.8 on 2026-04-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_medicaltestresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='genepredictionreport',
            name='confidence_interval',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='genepredictionreport',
            name='f1_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='genepredictionreport',
            name='precision',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='genepredictionreport',
            name='recall',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='genepredictionreport',
            name='top_affecting_genes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
