# Generated by Django 5.2.8 on 2026-04-17 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_twinsimulationreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twinsimulationreport',
            name='hits',
        ),
    ]
