# Generated by Django 5.2.8 on 2026-04-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_genepredictionreport_confidence_interval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genepredictionreport',
            name='input_features',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
