# Generated by Django 5.2.8 on 2026-04-17 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_twinsimulationreport_hits'),
        ('api', '0012_genepredictionreport_input_features'),
    ]

    operations = [
    ]
